export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i className="fa-solid fa-tags"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className="fa-solid fa-gear"></i>
export const logout = <i className="fa-solid fa-arrow-right-from-bracket"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const money = <i className="fa-solid fa-money-bill"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
export const piggy = <i className="fa-solid fa-piggy-bank"></i>
export const yt = <i className="fa-brands fa-youtube"></i>
export const card = <i className="fa-brands fa-cc-visa"></i>
export const users = <i className="fa-solid fa-users-between-lines"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calendar = <i className="fa-solid fa-calendar"></i>
export const comment = <i className="fa-solid fa-comment"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const takeout = <i className="fa-solid fa-utensils"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const book = <i className="fa-solid fa-book-open"></i>
export const food = <i className="fa-solid fa-bowl-food"></i>
export const medical = <i className="fa-solid fa-briefcase-medical"></i>
export const tv = <i className="fa-solid fa-tv"></i>
export const circle = <i className="fa-solid fa-circle-dot"></i>
export const sportsbet = <i className="fa-solid fa-dice"></i>
export const gift = <i className="fa-solid fa-gift"></i>
export const returns = <i className="fa-solid fa-basket-shopping"></i>
export const shopping = <i className="fa-solid fa-cart-shopping"></i>
export const misc = <i className="fa-solid fa-ellipsis"></i>
export const travel = <i className="fa-solid fa-plane-departure"></i>
export const house = <i className="fa-solid fa-house"></i>
export const school = <i className="fa-solid fa-graduation-cap"></i>
export const X = <i className="fa-regular fa-circle-xmark"></i>
export const chart = <i className="fa-solid fa-chart-simple"></i>